### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/mercedestrenz#52]
Congratulations on finishing milestone 2!  Nice work on the Tests on Python and setting up your R repo!  Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.
PS Milestone 2 is out of 70.

Python repo looks great. 

Tests ran perfectly for python! Great job! 
<img width="907" alt="Screenshot 2023-01-23 at 3 25 27 PM" src="https://user-images.githubusercontent.com/45893111/214176069-03054e40-a419-45f2-9be0-a9c2ccd741f6.png">

- [x] #63

Commits look great and are spread out.

**Comment by kellywujy** [comment]
R README.md updated
