### ISSUE TITLE
License choice discussion (R & Python)

### ISSUE THREAD

**Issue by mozhao0331** [UBC-MDS/mercedestrenz#76]
Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly discussed.

**Comment by tieandrews** [comment]
Discussion here: https://github.com/UBC-MDS/mercedestrenzr/issues/41

**Comment by mozhao0331** [comment]
In conclusion, we decide to use the MIT license.
