### ISSUE TITLE
Initiate a package review request

### ISSUE THREAD

**Issue by mozhao0331** [UBC-MDS/mercedestrenz#77]
Each team must initiate a review request by opening an issue per package in the [UBC-MDS/software-review-2022](https://github.com/UBC-MDS/software-review-2022) repository.

For initiating a reviewing request in R, use [this template](https://github.com/ropensci/software-review/blob/master/.github/ISSUE_TEMPLATE/A-submit-software-for-review.md).

For initiating a reviewing request in Python, use the template under Submit Software for Review at [this link](https://github.com/pyOpenSci/software-review/blob/main/.github/ISSUE_TEMPLATE/submit-software-for-review.md).

**Comment by spencergerlach** [comment]
Done here: https://github.com/UBC-MDS/software-review-2023/issues/26
