### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/mercedestrenz#82]
**Congratulations on finishing milestone 3!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

### 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}
**Comment:** Make sure to remove the example test in test-important_mercedes_features.R

### 1. GitHub actions workflow for continuous integration
rubric={mechanics:10}
Good Job!
### 2. GitHub actions workflow for continuous deployment
rubric={mechanics:10}
Good Job!

### 3. Documentation
rubric={reasoning:10}
Good Job!

## Specific expectations for this milestone 
rubric={mechanics:10}
Good Job!

## Submission instructions
rubric={mechanics:10}
Good Job!

**Comment by mozhao0331** [comment]
Remove the file `test-important_mercedes_features.R`.
