### ISSUE TITLE
Update Readme.md with authors and usage

### ISSUE THREAD

**Issue by tieandrews** [UBC-MDS/mercedestrenz#9]

**Comment by mozhao0331** [comment]
1. a summary paragraph that describes the project at a high level 
(done)

2. a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)
(done)

3. a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).
(done)
